### ISSUE TITLE
Allow For Particle Parameters

### ISSUE THREAD

**Issue by forgeno** [EnocraftMC/UltraCosmetics#10]
We want to investigate and implement parameters for redstone particles to allow for finer adjustment to effects.

We want to be able to adjust:
- offset from center particles spawn in
- size of each redstone particle
- redstone particle decay time

**Comment by cxbrettbaker** [comment]
The only functionality missing was specified size, I've added that now.

Redstone particle decay time seems to be intrinsically linked to the size of the particle, thus this new addition addresses that as well.
